/* Generated By:JJTree: Do not edit this line. ASTBNFTryBlock.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTBNFTryBlock extends JJTreeNode{
  public ASTBNFTryBlock(int id) {
    super(id);
  }

  public ASTBNFTryBlock(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b84a79ec2d29fe80861d956aa1ff1992 (do not edit this line) */
