/* Generated By:JJTree: Do not edit this line. ASTBNFZeroOrOne.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTBNFZeroOrOne extends JJTreeNode{
  public ASTBNFZeroOrOne(int id) {
    super(id);
  }

  public ASTBNFZeroOrOne(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e550cf97ed8825ba2419caecfecd53f7 (do not edit this line) */
