/* Generated By:JJTree: Do not edit this line. ASTBNFOneOrMore.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTBNFOneOrMore extends JJTreeNode{
  public ASTBNFOneOrMore(int id) {
    super(id);
  }

  public ASTBNFOneOrMore(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3f25f74309ef8c68a09e4a412e330e46 (do not edit this line) */
