/* Generated By:JJTree: Do not edit this line. ASTBNFParenthesized.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTBNFParenthesized extends JJTreeNode{
  public ASTBNFParenthesized(int id) {
    super(id);
  }

  public ASTBNFParenthesized(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=314e722d0e2a47b06bf2ef9c2d5e1547 (do not edit this line) */
