/* Generated By:JJTree: Do not edit this line. ASTBNFChoice.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTBNFChoice extends JJTreeNode{
  public ASTBNFChoice(int id) {
    super(id);
  }

  public ASTBNFChoice(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c2fbdf0263bb0cec363aaaac239a4515 (do not edit this line) */
