/* Generated By:JJTree: Do not edit this line. ASTBNFNonTerminal.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTBNFNonTerminal extends JJTreeNode{
  public ASTBNFNonTerminal(int id) {
    super(id);
  }

  public ASTBNFNonTerminal(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=de66ed9b7ae0958ad37f20c75a49b8fa (do not edit this line) */
