/* Generated By:JJTree: Do not edit this line. ASTBNFLookahead.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTBNFLookahead extends JJTreeNode{
  public ASTBNFLookahead(int id) {
    super(id);
  }

  public ASTBNFLookahead(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7b47aade0618278c8f1e479398918170 (do not edit this line) */
