/* Generated By:JJTree: Do not edit this line. ASTBNFAssignment.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTBNFAssignment extends JJTreeNode{
  public ASTBNFAssignment(int id) {
    super(id);
  }

  public ASTBNFAssignment(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f60d1f1ada63c2b9f7c112a17b223eda (do not edit this line) */
