/* Generated By:JJTree: Do not edit this line. ASTBNFZeroOrMore.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTBNFZeroOrMore extends JJTreeNode{
  public ASTBNFZeroOrMore(int id) {
    super(id);
  }

  public ASTBNFZeroOrMore(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=14f3d3b0c661cc1af570ea249cff7a78 (do not edit this line) */
