/* Generated By:JJTree: Do not edit this line. ASTBNFSequence.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTBNFSequence extends JJTreeNode{
  public ASTBNFSequence(int id) {
    super(id);
  }

  public ASTBNFSequence(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2a07bd03ea267a128e17342a6ed57d47 (do not edit this line) */
