/* Generated By:JJTree: Do not edit this line. ASTCharDescriptor.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTCharDescriptor extends JJTreeNode{
  public ASTCharDescriptor(int id) {
    super(id);
  }

  public ASTCharDescriptor(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bfe254145a9c5dc4534a06cb71f16903 (do not edit this line) */
