/* Generated By:JJTree: Do not edit this line. ASTPrimaryExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTPrimaryExpression extends JJTreeNode{
  public ASTPrimaryExpression(int id) {
    super(id);
  }

  public ASTPrimaryExpression(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a6538117f704e663827def947ae38942 (do not edit this line) */
