/* Generated By:JJTree: Do not edit this line. ASTProductions.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTProductions extends JJTreeNode{
  public ASTProductions(int id) {
    super(id);
  }

  public ASTProductions(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f9cff46ae95e50192d68d0c4592bfab3 (do not edit this line) */
