/* Generated By:JJTree: Do not edit this line. ASTREChoice.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTREChoice extends JJTreeNode{
  public ASTREChoice(int id) {
    super(id);
  }

  public ASTREChoice(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4fef48b5a3ba71ab22e59bcfa0f84948 (do not edit this line) */
