/* Generated By:JJTree: Do not edit this line. ASTRESequence.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTRESequence extends JJTreeNode{
  public ASTRESequence(int id) {
    super(id);
  }

  public ASTRESequence(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b48e633d89d2bb89ac8e4d0fbd8dabfc (do not edit this line) */
