/* Generated By:JJTree: Do not edit this line. ASTREOneOrMore.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTREOneOrMore extends JJTreeNode{
  public ASTREOneOrMore(int id) {
    super(id);
  }

  public ASTREOneOrMore(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=09f79b5ebb9dcae90127215a21a6c0de (do not edit this line) */
