/* Generated By:JJTree: Do not edit this line. ASTREZeroOrMore.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTREZeroOrMore extends JJTreeNode{
  public ASTREZeroOrMore(int id) {
    super(id);
  }

  public ASTREZeroOrMore(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6ef04b3d9f7e3ebe8416ca68d10558a4 (do not edit this line) */
