/* Generated By:JJTree: Do not edit this line. ASTREStringLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTREStringLiteral extends JJTreeNode{
  public ASTREStringLiteral(int id) {
    super(id);
  }

  public ASTREStringLiteral(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d504079c75a5e75171f0d676db070728 (do not edit this line) */
