/* Generated By:JJTree: Do not edit this line. ASTRECharList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTRECharList extends JJTreeNode{
  public ASTRECharList(int id) {
    super(id);
  }

  public ASTRECharList(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9b5f9f447a5f53ad9d36efd101d209d3 (do not edit this line) */
