/* Generated By:JJTree: Do not edit this line. ASTRRepetitionRange.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTRRepetitionRange extends JJTreeNode{
  public ASTRRepetitionRange(int id) {
    super(id);
  }

  public ASTRRepetitionRange(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=094da1c1a92e072d76de65ecdd3c53bb (do not edit this line) */
