/* Generated By:JJTree: Do not edit this line. ASTREZeroOrOne.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTREZeroOrOne extends JJTreeNode{
  public ASTREZeroOrOne(int id) {
    super(id);
  }

  public ASTREZeroOrOne(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=41f924b3939b9b7d77a57c65749b87f2 (do not edit this line) */
