/* Generated By:JJTree: Do not edit this line. ASTREParenthesized.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTREParenthesized extends JJTreeNode{
  public ASTREParenthesized(int id) {
    super(id);
  }

  public ASTREParenthesized(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aac5904546e8b080eb42ddb3de100b5e (do not edit this line) */
