/* Generated By:JJTree: Do not edit this line. ASTREReference.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTREReference extends JJTreeNode{
  public ASTREReference(int id) {
    super(id);
  }

  public ASTREReference(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1bdf35795649b1b54b5ae3f4d2470539 (do not edit this line) */
