/* Generated By:JJTree: Do not edit this line. ASTRE.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTRE extends JJTreeNode{
  public ASTRE(int id) {
    super(id);
  }

  public ASTRE(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d2d4265a42285841e98b80ae1d43c14a (do not edit this line) */
