/* Generated By:JJTree: Do not edit this line. ASTREEOF.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTREEOF extends JJTreeNode{
  public ASTREEOF(int id) {
    super(id);
  }

  public ASTREEOF(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fc04c26e257463f55cae1f88aed5942c (do not edit this line) */
