/* Generated By:JJTree: Do not edit this line. ASTRESpec.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTRESpec extends JJTreeNode{
  public ASTRESpec(int id) {
    super(id);
  }

  public ASTRESpec(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4b83f8d92eccd3f2202dba518ada4c97 (do not edit this line) */
