/* Generated By:JJTree: Do not edit this line. ASTRENamed.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTRENamed extends JJTreeNode{
  public ASTRENamed(int id) {
    super(id);
  }

  public ASTRENamed(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=577f8926d12bc0ad53eda8d73f45f74d (do not edit this line) */
