/* Generated By:JJTree: Do not edit this line. ASTTokenDecls.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTTokenDecls extends JJTreeNode{
  public ASTTokenDecls(int id) {
    super(id);
  }

  public ASTTokenDecls(JJTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b120d135d41678a7e636870da2a0b65c (do not edit this line) */
